env:
  global:
    - LC_CTYPE=en_US.UTF-8

matrix:
  include:
    - &podspec
      name: CocoaPods Lint
      os: osx
      language: objective-c
      osx_image: xcode10.2
      script:
        - pod lib lint --allow-warnings
    - &swiftpm
      name: SwiftPM / Darwin / Swift 5.0
      os: osx
      language: generic
      osx_image: xcode10.2
      script:
        - swift build
        - swift test
